Refine CRDs for wider shareout
cloudfoundry/cf-crd-explorations pull request #67
Opened 2021-08-11 00:07 UTC by gnovv

https://github.com/cloudfoundry/cf-crd-explorations/issues/12

Co-authored-by: Akira Wong <wakira@vmware.com>

2021-08-11 17:13 UTC, Birdrock reviewed
Generally looks pretty good for sharing and feedback. The comments are a nice touch. Do note that these CRs will not be compatible with the spike shim - at the least, they don't have corresponding CRDS. If these are intended solely as examples going forward, that should be fine.

What conventions are there for the `kind` field? Are multiple leading capitals acceptable in Kubernetes world?

2021-08-11 17:25 UTC, tcdowney commented
> What conventions are there for the kind field? Are multiple leading capitals acceptable in Kubernetes world?

@Birdrock 

I think it's ok, here's [their guidance on it](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions):

> Acronyms should similarly only be used when extremely commonly known. All letters in the acronym should have the same case, using the appropriate case for the situation. 

As long as we assume the "CF" acronym is commonly known by our intended audience. 🙂 

Also here's some real world examples of Kinds like this:

```
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
apiservices                                    apiregistration.k8s.io/v1              false        APIService
csidrivers                                     storage.k8s.io/v1                      false        CSIDriver
ipamblocks                                     crd.projectcalico.org/v1               false        IPAMBlock
```

2021-08-12 21:42 UTC, heycait commented
After evaluating the GUID formats with current clients, @acosta11 and I are proposing the following:

```
 labels:
    apps.cloudfoundry.org/appName: my-app-name
 name: 14dcda7d-my-app-name
```

The resource name itself would consist of a hashed version of the org+space+app name in order to account for length limits and allow us to take advantage optimistic locking.


See: https://github.com/cloudfoundry/cf-k8s-api/issues/2#issuecomment-897985185

2021-08-17 23:19 UTC, matt-royal requested changes
I made some comments on some possible changes. Please take a look.

2021-08-17 23:19 UTC, matt-royal commented on config/samples/cf-crds-post-spike/app.yaml
> +  lifecycle: # taken from cf-for-k8s I think we should leave it with a note pointing out how it works in cf-for-k8s
This comment isn't necessary given the comment directly below

2021-08-17 23:19 UTC, matt-royal commented on config/samples/cf-crds-post-spike/app.yaml
> +  - type: Restarting # Allows the us to implement the v3 restart app endpoint: https://v3-apidocs.cloudfoundry.org/version/3.100.0/index.html#restart-an-app
Should be "Allows us" not "Allows the us"

2021-08-17 23:19 UTC, matt-royal commented on config/samples/cf-crds-post-spike/build.yaml
> +    kind: CFApp
I don't think we've discussed this, but we could remove both kind and apiVersion for now and only add them if/when we want to support other types in here or other versions. This would be true for most/all ref fields

2021-08-17 23:19 UTC, matt-royal commented on config/samples/cf-crds-post-spike/droplet.yaml
> +    web: bundle exec rackup config.ru -p $PORT -o 0.0.0.0
I remember commenting that this might be simpler/clearer as a list of objects with "type" and "command" fields. That format is also easier to extend in the future if we want to add more fields. We would have to validate against duplicate processType[].type values, but I think the extensibility makes it worth it.

2021-08-17 23:19 UTC, matt-royal commented on config/samples/cf-crds-post-spike/package.yaml
> +  conditions: # These should be managed by a controller, not the shim
We can probably remove this comment since it's an implementation concern and not a schema concern, and may confuse readers.

2021-08-17 23:43 UTC, gnovv commented
> I made some comments on some possible changes. Please take a look.
Thank you @matt-royal!
Made requested changes: 
https://github.com/cloudfoundry/cf-crd-explorations/pull/67/commits/dc8ee89c0df97f1722e4f5e1fbdc9e97a55a7ce3

2021-08-31 20:49 UTC, merged